"""
Posts the triage analysis back to the Sentinel incident as a comment.
Optionally closes the incident if classified as BenignPositive.
"""

from sentinel_api import post_incident_comment, update_incident_status
from state import TriageState


def _format_comment(state: TriageState) -> str:
    """
    Formats the triage results into a structured, readable Sentinel comment.
    """
    entities = state.get("entities", {})
    cti = state.get("cti_results", {})
    kql_queries = state.get("kql_queries", [])

    # Build entity summary
    entity_lines = []
    if entities.get("ips"):
        entity_lines.append(f"**IPs:** {', '.join(entities['ips'])}")
    if entities.get("urls"):
        entity_lines.append(f"**URLs:** {', '.join(entities['urls'][:3])}")
    if entities.get("hashes"):
        entity_lines.append(f"**Hashes:** {', '.join(entities['hashes'][:3])}")
    if entities.get("usernames"):
        entity_lines.append(f"**Users:** {', '.join(entities['usernames'])}")

    # Build CTI summary
    cti_lines = []
    for ip_report in cti.get("ip_reports", []):
        if "error" not in ip_report:
            score = ip_report.get("abuse_score", 0)
            flag = "🔴" if score > 50 else ("🟡" if score > 10 else "🟢")
            cti_lines.append(
                f"{flag} IP {ip_report['ioc']}: AbuseIPDB score {score}/100 "
                f"({ip_report.get('usage_type', 'Unknown')} | {ip_report.get('country', '?')})"
            )
    for url_report in cti.get("url_reports", []):
        if "error" not in url_report:
            mal = url_report.get("malicious", 0)
            flag = "🔴" if mal > 3 else ("🟡" if mal > 0 else "🟢")
            cti_lines.append(
                f"{flag} URL {url_report['ioc'][:60]}: {mal}/{url_report.get('total', '?')} VT detections"
            )

    comment = f"""## Autonomous Triage Agent Report

**Verdict:** `{state.get('classification', 'Undetermined')}`

---

### Summary
{state.get('triage_summary', 'No summary available.')}

### MITRE ATT&CK Analysis
{state.get('mitre_analysis', 'No MITRE analysis available.')}

---

### Extracted Entities
{chr(10).join(entity_lines) or "No entities extracted."}

### CTI Enrichment
{chr(10).join(cti_lines) or "No CTI results available."}

---

### KQL Hunting Queries
Copy and run these in Sentinel → Logs:

```kql
{chr(10).join(kql_queries[:2]) or "No queries generated."}
````

---

_Generated by sentinel-triage-agent | LangGraph + Gemini + VirusTotal + AbuseIPDB_
"""
    return comment


def writeback_node(state: TriageState) -> dict:
    """Posts comment and optionally closes the incident."""
    incident_id = state["incident_id"]
    comment_posted = False
    incident_closed = False
    errors = list(state.get("errors", []))

    # ── Post the triage comment ────────────────────────────────────────────────
    try:
        comment_text = _format_comment(state)
        post_incident_comment(incident_id, comment_text)
        comment_posted = True
    except Exception as e:
        errors.append(f"Comment post failed: {str(e)}")

    # ── Close the incident if BenignPositive ──────────────────────────────────
    if state.get("classification") == "BenignPositive" and comment_posted:
        try:
            update_incident_status(
                incident_id=incident_id,
                new_status="Closed",
                classification="BenignPositive",
            )
            incident_closed = True
        except Exception as e:
            errors.append(f"Status update failed: {str(e)}")

    return {
        "comment_posted": comment_posted,
        "incident_closed": incident_closed,
        "errors": errors,
    }