"""
Posts the triage analysis back to the Sentinel incident as a comment.
Closure is deferred until human review and approval.
"""

import hashlib

import structlog

from sentinel_api import (fetch_incident_comments, post_incident_comment,
                          update_incident_status)
from state import TriageState

logger = structlog.get_logger(__name__)

_HASH_TAG = "<!--sentinel-triage-agent-hash:{}-->"


def _format_entity_lines(entities: dict) -> list[str]:
    """
    Builds markdown lines summarizing extracted entities.

    Args:
        entities: The extracted entities dictionary.

    Returns:
        A list of markdown strings for the entities.
    """
    lines = []
    if entities.get("ips"):
        lines.append(f"**IPs:** {', '.join(entities['ips'])}")
    if entities.get("urls"):
        lines.append(f"**URLs:** {', '.join(entities['urls'][:3])}")
    if entities.get("hashes"):
        lines.append(f"**Hashes:** {', '.join(entities['hashes'][:3])}")
    if entities.get("usernames"):
        lines.append(f"**Users:** {', '.join(entities['usernames'])}")
    return lines


def _format_cti_lines(cti: dict) -> list[str]:
    """
    Builds markdown lines summarizing CTI enrichment results.

    Args:
        cti: The CTI enrichment results dictionary.

    Returns:
        A list of markdown strings for the CTI results.
    """
    lines = []
    for ip_report in cti.get("ip_reports", []):
        if "error" not in ip_report:
            score = ip_report.get("abuse_score", 0)
            flag = "🔴" if score > 50 else ("🟡" if score > 10 else "🟢")
            lines.append(
                f"{flag} IP {ip_report['ioc']}: AbuseIPDB score {score}/100 "
                f"({ip_report.get('usage_type', 'Unknown')} | {ip_report.get('country', '?')})"
            )
    for url_report in cti.get("url_reports", []):
        if "error" not in url_report:
            mal = url_report.get("malicious", 0)
            flag = "🔴" if mal > 3 else ("🟡" if mal > 0 else "🟢")
            lines.append(f"{flag} URL {url_report['ioc'][:60]}: {mal} VT detections")
    return lines


def _format_mitre_table(mitre_techniques: list) -> list[str]:
    """
    Builds a markdown table of mapped MITRE ATT&CK techniques.

    Args:
        mitre_techniques: A list of verified MITRE technique dictionaries.

    Returns:
        A list of markdown strings forming the table.
    """
    if not mitre_techniques:
        return ["_No specific MITRE techniques mapped._"]

    lines = [
        "| Tactic | Technique ID | Technique Name | Confidence | Status |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ]
    for tech in mitre_techniques:
        status_flag = "⚠️ Unverified" if tech.get("unverified") else "✅ Verified"
        tactic_name = tech.get("tactic", "Unknown")
        lines.append(
            f"| {tactic_name} | `{tech['technique_id']}` | {tech['name']} | {tech['confidence']}% | {status_flag} |"
        )
    return lines


def _format_comment(state: TriageState) -> str:
    """
    Formats the triage results into a structured, readable Sentinel comment.

    Args:
        state: The current TriageState dictionary.

    Returns:
        The formatted markdown comment string.
    """
    entity_lines = _format_entity_lines(state.get("entities", {}))
    cti_lines = _format_cti_lines(state.get("cti_results", {}))
    mitre_tech_lines = _format_mitre_table(state.get("mitre_techniques", []))

    review_tag = ""
    if state.get("classification") == "BenignPositive":
        review_tag = "\n\n**Review status:** Pending Analyst Review"

    comment = f"""## Autonomous Triage Agent Report

**Verdict:** `{state.get('classification', 'Undetermined')}`
{review_tag}

---

### Summary
{state.get('triage_summary', 'No summary available.')}

### MITRE ATT&CK Analysis
{state.get('mitre_analysis', 'No MITRE analysis available.')}

#### Mapped MITRE ATT&CK Techniques
{chr(10).join(mitre_tech_lines)}

---

### Extracted Entities
{chr(10).join(entity_lines) or "No entities extracted."}

### CTI Enrichment
{chr(10).join(cti_lines) or "No CTI results available."}

---

### KQL Hunting Queries
Copy and run these in Sentinel → Logs:

```kql
{chr(10).join(state.get("kql_queries", [])[:2]) or "No queries generated."}
```

---

_Generated by sentinel-triage-agent_
"""
    return comment


def _comment_hash(comment: str) -> str:
    """
    Returns the SHA-256 hex digest of a comment body.

    Args:
        comment: The comment string to hash.

    Returns:
        The SHA-256 hex digest string.
    """
    return hashlib.sha256(comment.encode()).hexdigest()


def _comment_already_posted(incident_id: str, fingerprint: str) -> bool:
    """
    Checks whether any existing comment already contains fingerprint.

    Args:
        incident_id: The ID of the Sentinel incident.
        fingerprint: The unique hash fingerprint to check for.

    Returns:
        True if the comment already exists, False otherwise.
    """
    for c in fetch_incident_comments(incident_id):
        message = c.get("properties", {}).get("message", "")
        if fingerprint in message:
            return True
    return False


def writeback_node(state: TriageState) -> dict:
    """
    Posts comment and defers incident closure until review.

    Args:
        state: The current TriageState dictionary.

    Returns:
        A dictionary containing state updates for the writeback node.
    """
    logger.info("node_entry", node="writeback")
    incident_id = state["incident_id"]
    comment_posted = False
    incident_closed = False
    errors = []

    # ── Post the triage comment ────────────────────────────────────────────────
    try:
        comment_text = _format_comment(state)
        digest = _comment_hash(comment_text)
        fingerprint = _HASH_TAG.format(digest)

        if _comment_already_posted(incident_id, fingerprint):
            comment_posted = True  # already exists, nothing to do
        else:
            post_incident_comment(incident_id, comment_text + "\n" + fingerprint)
            comment_posted = True
    except Exception as e:
        logger.error("node_error", node="writeback", exc_info=True)
        errors.append(f"Comment post failed: {str(e)}")

    logger.info("node_exit", node="writeback")
    return {
        "comment_posted": comment_posted,
        "incident_closed": incident_closed,
        "errors": errors,
    }


def close_review_node(state: TriageState) -> dict:
    """
    Executes the Sentinel close action only after human approval.
    The graph is paused before this node so an analyst can confirm the decision.

    Args:
        state: The current TriageState dictionary.

    Returns:
        A dictionary containing state updates for the close review node.
    """
    logger.info("node_entry", node="close_review")
    incident_closed = False
    errors = []

    if state.get("close_approved"):
        classification = state.get("classification", "Undetermined")
        try:
            update_incident_status(
                incident_id=state["incident_id"],
                new_status="Closed",
                classification=classification,
            )
            incident_closed = True
        except Exception as e:
            logger.error("node_error", node="close_review", exc_info=True)
            errors.append(f"Close approval failed: {str(e)}")

    logger.info("node_exit", node="close_review")
    return {
        "incident_closed": incident_closed,
        "errors": errors,
    }
